### ISSUE TITLE
None Question Input Generate Interesting Responses

### ISSUE THREAD

**Issue by Proteusiq** [kaustubhdhole/natural-dont-know#2]
Testing the behaviour of the model using random weird inputs give interesting results
![image](https://user-images.githubusercontent.com/14926709/103635897-7b040500-4f49-11eb-9dbb-31b144834185.png)

Question:
   Is there a way to prune the model to avoid such responses?

**Comment by kaustubhdhole** [comment]
Hey, thanks for sharing your test results!

_Is there a way to prune the model to avoid such responses?_

- You could probably fine-tune the model further on maybe non-questions, single/two/three words and pair them with a static dont-know response. Or you could filter them out at the input itself with a few quick heuristics, like keep only those which are interrogatives (sentence classifiers) or have a WH-word type, etc.


We have trained it only on questions, so the best outputs would be for questions itself. One thing that you'll notice is that adding a SPACE and a Question_Mark generates better responses so, at least you could ensure that there's a " ?" at the end of your inputs. 

Query: suger high ?
Response: I'm not really sure if it Is high.

Query: What is better ?
Response: I'm not sure what better , less painful and more satisfying is.

Query: 42 ?
Response: I'm not sure if i Can give some advice on how to get the best

Query: tanzania ?
Response: I'm not actually sure what the best way to travel in that place is.

Query: afroamerican ?
Response: I'm not actually sure what the difference between afroamerican and latino
